In [ ]:
import numpy as np

# 1. find the shape and type of an array z = (a, a*2)




In [ ]:
z = (a,a*2)
z

(array([ 4, -3, -2,  1,  3,  4]), array([ 8, -6, -4,  2,  6,  8]))

# 2. An array a = (4, -3, -2, 1, 3, 4). 
1.   find sum of the elements in the array 
2.   find the small and big elements of the array
3.   find the mean and standard deviation of the array elements
4.   find the index of the biggest and smallest elements of the array



In [ ]:
a = np.array([4, -3, -2, 1, 3, 4])

In [ ]:
a.sum()  # it will find the sum

7

In [ ]:
a.min()  # it will find small element in array

-3

In [ ]:
a.max()  #it will find large element in array

4

In [ ]:
a.mean()  #it will find the mean

1.1666666666666667

In [ ]:
a.std()  # it will find standard deviation

2.793842435706702

In [ ]:
a.argmin()  # it will find index of smallest element in array

1

In [ ]:
a.argmax()  # it will find index of largest element in array

0

#  3. find the dot product of (2j, 3j), (3j, 2j)

In [ ]:
np.dot([2j,3j],[3j,2j])   # it will find dot product between a and b

(-12+0j)

#4. create an array which contain square of all integer numbers between 0 and 13.  



In [ ]:
s=np.arange(13)**2  # each element in the array will be squared
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

# 5. Use bracke notation to get value particular index
*  s[4] 
* s[:5] 
* s[2:6] 
* s[-4]
* s[-4:-1] 
* s[-4: ] 
* s[-5::-2] 
* s[-5::2] 

In [ ]:
s[4]   # get element from index 4

16

In [ ]:
s[:5]  # it get from start and end before 5

array([ 0,  1,  4,  9, 16])

In [ ]:
s[2:6]  # it will start from 2 before 6 

array([ 4,  9, 16, 25])

In [ ]:
s[-4]  # it is negative indexing 

81

In [ ]:
s[-4:-1] # it will take negative index ; from -4 till -1

array([ 81, 100, 121])

In [ ]:
s[-4: ]  # it will take -4 till last

array([ 81, 100, 121, 144])

In [ ]:
s[-5::-2] #from -5 loc to 0 loc with space of 2; -2:implies it moves in negative 

array([64, 36, 16,  4,  0])

In [ ]:
s[-5::2] #from -5 loc to last loc with space of 2; 2:implies it moves in positive 

array([ 64, 100, 144])